name: "Terraform-Plan-Dev-Release"

on:
  push:
    branches:
      - develop

jobs:
  terraform:
    name: "Terraform Apply in Dev"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "eu-central-1"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        id: init
        run: |
          cd terraform/resources/
          terraform init -backend-config=bucket=tf-state-soham-poc-bucket -backend-config=key=dev/terraform.tfstate

      - name: Terraform Apply
        id: apply
        if: github.event_name == 'push'
        run: terraform apply --var-file=../environments/dev/dev.tfvars -auto-approve
        continue-on-error: true

      - name: Terraform Apply Status
        if: steps.apply.outcome == 'failure'
        run: exit 1
