name: "Terraform-Plan-Prod-Release"

on:
  pull_request:
    branches:
      - master

jobs:
  terraform:
    name: "Terraform Plan in Prod"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "eu-central-1"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        id: init
        run: |
          cd terraform/resources/
          terraform init -backend-config=bucket=tf-state-soham-poc-bucket -backend-config=key=prod/terraform.tfstate

      - name: Terraform Plan
        id: plan
        run: |
          cd terraform/resources/
          terraform plan --var-file=../environments/prod/prod.tfvars -no-color
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1
